services:
  web:
    build: ./config
    container_name: web
    volumes:
      - ./:/var/www/html

    ports:
      - 80:80
  db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: qlbh
      MYSQL_USER: kiet
      MYSQL_PASSWORD: 1
    ports:
      - 30:3036
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN

volumes:
  db:
    